---
title: "503_hw2"
author: "Xuechun Wang"
date: "9/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ggplot2

```{r}
library("readxl")
#import the data set:
mydata = read_excel("~/Desktop/503_hw2_data.xlsx")
n<-dim(mydata)[1]
mydata<-mydata[1:(n-4),]
#summary(mydata)
```

Total Energy consumption in the US:
```{r}
library(ggplot2)
library(dplyr)
newdata_1 = mydata[,c(-8,-11)]
n = length(names(newdata_1))-1
data <- data.frame(group=names(newdata_1)[2:n],
                   value=as.numeric(newdata_1[52,])[2:n])



# Compute the position of labels
data <- data %>% 
  arrange(desc(group)) %>%
  mutate(prop = round(value / sum(data$value) *100),2) %>%
  mutate(ypos = round(cumsum(prop) - 0.5*prop ),2)

# Basic piechart
ggplot(data, aes(x="", y=prop, fill=group)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position="left") +
  labs(x = NULL, y = NULL, fill = NULL, 
         title = "Energy Consumption Shares") +
  
  geom_text(aes(y = ypos, label = "")) +
  scale_fill_brewer(palette="Set3")
```

```{r}
newdata_2 = mydata[,c(-1,-3,-4,-5,-6,-7,-11,-12,-13)]
names(newdata_2) <- c("Natural Gas", "Petroleum", "Ethanol","Electricity")
```



```{r}
cormat <- round(cor(newdata_2),2)
#head(cormat)
# Get lower triangle of the correlation matrix
  get_lower_tri<-function(cormat){
    cormat[upper.tri(cormat)] <- NA
    return(cormat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  
upper_tri <- get_upper_tri(cormat)
#upper_tri
```

```{r}
# Melt the correlation matrix
library(reshape2)
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Heatmap
library(ggplot2)
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+ labs(x = NULL, y = NULL, fill = NULL, 
         title = "Correlation Heat Plots") +
 scale_fill_gradient2(low = "lightblue", high = "pink", mid = "white", 
   midpoint = 0.9, limit = c(0.8,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
```

```{r}
mydata = read_excel("~/Desktop/503_hw2_data.xlsx")
n<-dim(mydata)[1]
mydata<-mydata[1:(n-5),]
#summary(mydata)
```

```{r}
library(plotly)
mydata$code = state.abb[match(mydata$State, state.name)]
mydata$total = mydata$`Total (Trillion Btu)`
df = mydata
df$hover <- with(df, paste(State, '<br>', "Natural Gas:",df$`Natural gas (Trillion Btu)`, "Petroleum: ",df$`Total petroleum (Trillion Btu)`, "<br>","Ethanol: ", df$`Ethanol (Trillion Btu)`,"Electricity",df$`Electricity (Trillion Btu)`,"<br>"))
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

p <- plot_geo(df, locationmode = 'USA-states') %>%
  add_trace(
    z = ~total, text = ~hover, locations = ~code,
    color = ~total, colors = 'Purples'
  ) %>%
  colorbar(title = "Millions USD") %>%
  layout(
    title = 'US Energy Consumption by State<br>(Hover for breakdown)',
    geo = g
  )

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
chart_link = api_create(p, filename="choropleth-hw1")
chart_link
```



```{r}
write.csv(df,'mydf.csv')
```

